### ISSUE TITLE
Score Calculation Bug

### ISSUE THREAD

**Issue by epicci23** [ojuz/ojuz-contribute#12]
When I get accepted from 2 different subtasks from different submissions (in same problem),  my score should be calculated  as the sum of these subtasks. 
But, the site calculates my score as the maximum of those submissions.

**Comment by tncks0121** [comment]
Not a bug but a feature, sorry.. Note that this website was implemented before IOI 2017 where that scoring was introduced, and it is hard to reimplement all those stuff
