### ISSUE TITLE
[BUG] Incorrect scoring for IOI 2011 Day 2 Parrots

### ISSUE THREAD

**Issue by Pyqe** [ojuz/ojuz-contribute#19]
In [https://oj.uz/problem/view/IOI11_parrots](https://oj.uz/problem/view/IOI11_parrots) the scoring for the last subtask should follow the scoring described in the task statement based on the value of the ratio P. However, the current scoring just directly takes the value of P as the score of that subtask

**Comment by tncks0121** [comment]
Thanks, it's now being rejudged
