### ISSUE TITLE
[FEATURE] Add a way to filter by problem type (e.g. find interactive problems)

### ISSUE THREAD

**Issue by dolphingarlic** [ojuz/ojuz-contribute#2]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to find interactive problems but then I have to sift through pages of batch problems.

**Describe the solution you'd like**
There should be a way to filter by problem type.

**Describe alternatives you've considered**
A way to filter by topic (like Codeforces) would also be nice but that's probably hard to implement since one would have to add topics to each problem. (Maybe a topic-suggestion system like Szkopul might work?)

**Additional context**
![szkopul](https://user-images.githubusercontent.com/31325319/78180150-a3af1980-7462-11ea-9be7-0b52bf28a8b8.png)

**Comment by tncks0121** [comment]
You can search like this: https://oj.uz/problems?search=&type=INTERACTIVE
