### ISSUE TITLE
[PROB] APIO 2024 Contest

### ISSUE THREAD

**Issue by Muaath5** [ojuz/ojuz-contribute#20]
[Github Archive for the contest (statements/solutions/explanations/testcases)](https://github.com/APIO-2024/apio2024_tasks)

Probably the problem is in the last task (communicational) which required submitting 2 codes in the main contest, I guess it could be compressed into 1 file which contains the 2 functions.

**Comment by tncks0121** [comment]
https://oj.uz/problems/source/652
