### ISSUE TITLE
[BUG] Incorrect scoring on JOI24 Tricolor

### ISSUE THREAD

**Issue by 8e7** [ojuz/ojuz-contribute#23]
**Describe the bug**
In the problem [JOI 24 Tricolor](https://oj.uz/problem/view/JOI24_tricolor), the grader does not score submissions according to the statement for the final subtask (with continuous scoring).

**To Reproduce**
Check submission [1074103](https://oj.uz/submission/1074103).
In line 130 of Anna.cpp, clearly L=34 is used. The score for L=34 according to the formula is 76 points. However the submission gets 83.2 points.

**Additional context**
The grader in the [official contest page](https://www2.ioi-jp.org/camp/2024/2024-sp-tasks/contest2/tricolor-cms.zip) seems to have the correct implementation.

**Comment by tncks0121** [comment]
Fixed, now rejudging all submissions, thanks
