### ISSUE TITLE
Wrong Test Cases For Subtask 1 Of IOI 2016 - DAY 1 - Shortcut

### ISSUE THREAD

**Issue by ALeonidou2005** [ojuz/ojuz-contribute#24]
The first subtask should only contain test case of n<=10, but it does not. Tests cases 1-30 of subtask 1 satisfy n<=10, but tests 31-38 do not. Tests 31-38 satisfy n<=100, and should only be tested on the next subtask (subtask 2).

**Comment by tncks0121** [comment]
It indeed was wrong, removed such tests. Not sure if I can rejudge all submissions, so I didn't

**Comment by tncks0121** [comment]
Decided to only rejudge your solution
