### ISSUE TITLE
[PROB] IOI 2003 Reverse

### ISSUE THREAD

**Issue by dolphingarlic** [ojuz/ojuz-contribute#3]
Please try to answer all the questions. You can request several problems at once, but in that case, the request should contain all the necessary information.

**Where does the problem come from?**
IOI 2003

**How to get test data?**
https://filebin.ca/5IHNK9OuEagK/ioi-03-reverse-1.zip

**If the problem contain subtasks, how to divide each input into subtasks?**
Tests 1-12 are worth 6 points each and tests 13-16 are worth 7 points each

**If the problem requires checker, how to get checker?**
The checker is in the package

**If the problem is interactive, how to get interactor?**
No

**If the problem requires library code, how to get that library code?**
No

**Additional context**
Apparently this problem is output-only, but Yandex required code to be submitted and run as well. Also, this is not the official grader.

**Comment by tncks0121** [comment]
https://oj.uz/problem/view/IOI03_reverse
