### ISSUE TITLE
[BUG] Checker error in problem IOI 2020 Day 0 - Painting Squares

### ISSUE THREAD

**Issue by SorahISA** [ojuz/ojuz-contribute#6]
**Describe the bug**
The checker for Subtask 4 in [*IOI 2020 Day 0 - Painting Squares*](https://oj.uz/problem/view/IOI20_squares) is wrong, it will give full points to solution which satisfied m <= 30 but only solutions with m <= 10 should get full points according to problem description.

![](https://i.imgur.com/X0Qlcsf.png)

**To Reproduce**
1. Submit a correct solution for [*IOI 2020 Day 0 - Painting Squares*](https://oj.uz/problem/view/IOI20_squares).
2. Set the value of K in your solution to be in range (10, 30].
3. See error.

**Expected behavior**
Get points in range [45, 97.25].

**Additional context**
Here is the link of [my submission](https://oj.uz/submission/441102).

**Comment by tncks0121** [comment]
You are correct, somehow partial scoring was off and I couldn't see that. Thanks for the report.
