### ISSUE TITLE
[PROB]

### ISSUE THREAD

**Issue by SlavicG** [ojuz/ojuz-contribute#7]
Please add Romanian Masters of Informatics 2021 problems. All statements can be found here: https://rmi.lbi.ro/rmi_2021/contest/problems/

And all solutions, checkers/graders and tests can be found here: https://rmi.lbi.ro/rmi_2021/contest/solutions/

**Comment by tncks0121** [comment]
Thanks, it's here https://oj.uz/problems/source/451
