### ISSUE TITLE
Add problems from info1cup 2021 2022

### ISSUE THREAD

**Issue by Sho-10** [ojuz/ojuz-contribute#8]
https://www.info1cup.com/archive/. The statements testcases are already on the site. When will the problems be added?

**Comment by tncks0121** [comment]
Hi, I was not aware about that, but it seems it's extremely difficult for me to upload those problems. For example, `coolrot` from info1cup 2021 requires writing a grader but even the sample grader is not provided. Thus I think I won't upload those problems in the near future, sorry for that.
