### ISSUE TITLE
[BUG] RMI20 peru has the wrong cases for each subtask.

### ISSUE THREAD

**Issue by LeonardoValente** [ojuz/ojuz-contribute#9]
In https://oj.uz/problem/view/RMI20_peru you can see that no one did any subtasks, and in accepted solutions they take the most time in the test data from the first subtask (where N is smaller).

This submission also confirms that N doesnt match the constraints for that subtask (N <= 2000): https://oj.uz/submission/597135

**Comment by tncks0121** [comment]
Indeed it is wrong, subtasks were in inverse order, sorry. All submissions are being rejudged now.
